using GLib;

namespace NizamSettings {
    public class PekwmMenuBuilder : Object {
        public static string build_hardcoded () {
            var sb = new StringBuilder();
            sb.append("# Generated by Nizam - DO NOT EDIT\n");
            sb.append("RootMenu = \"Nizam\" {\n");
            sb.append("\tEntry = \"Stop Window Manager\" { Actions = \"Exit\" }\n");
            sb.append("\tEntry = \"Restart\" { Actions = \"Restart\" }\n");
            sb.append("}\n\n");
            sb.append("WindowMenu = \"\" {\n\n");
            sb.append("\tEntry = \"Kill Window\" { Actions = \"Kill\" }\n");
            sb.append("}\n");
            return sb.str;
        }
    }
}
