using GLib;

namespace NizamSettings {
    public class WmKey : Object {
        public string accel;
        public string action;
        public bool enabled;

        public WmKey (string accel, string action, bool enabled) {
            this.accel = accel;
            this.action = action;
            this.enabled = enabled;
        }
    }

    public class WmState : Object {
        public HashTable<string, string> settings = new HashTable<string, string>(str_hash, str_equal);
        public PtrArray keys = new PtrArray();
    }

    public class PekwmRenderer : Object {
        private static string header () {
            return "# Generated by Nizam - DO NOT EDIT\n";
        }

        private static string get_setting (WmState st, string key, string fallback) {
            var v = st.settings.lookup(key);
            if (v == null || v.strip().length == 0) return fallback;
            return v;
        }

        private static string normalize_accel (string accel) {
            return accel.replace("-", " ").strip();
        }

        public string render_config (WmState st) {
            var sb = new StringBuilder();
            sb.append(header());

            sb.append("Files {\n");
            sb.append("    Keys = \"~/.pekwm/keys\"\n");
            sb.append("    Mouse = \"~/.pekwm/mouse\"\n");
            sb.append("    AutoProps = \"~/.pekwm/autoproperties\"\n");
            sb.append("    Icons = \"~/.pekwm/icons/\"\n");
            sb.append("}\n\n");

            sb.append("MoveResize {\n");
            sb.append("    EdgeAttract = \"10\"\n");
            sb.append("    EdgeResist = \"10\"\n");
            sb.append("    WindowAttract = \"5\"\n");
            sb.append("    WindowResist = \"5\"\n");
            sb.append("    OpaqueMove = \"True\"\n");
            sb.append("    OpaqueResize = \"False\"\n");
            sb.append("}\n\n");

            sb.append("Screen {\n");
            sb.append("    ShowFrameList = \"True\"\n");
            sb.append("    ShowStatusWindow = \"True\"\n");
            sb.append("    ShowStatusWindowCenteredOnRoot = \"False\"\n");
            sb.append("    ShowClientID = \"False\"\n");
            sb.append("    ShowWorkspaceIndicator = \"500\"\n");
            sb.append("    PlaceNew = \"True\"\n");
            sb.append("    FocusNew = \"True\"\n");
            sb.append("    FocusStealProtect = \"0\"\n\n");

            sb.append("    ReportAllClients = \"False\"\n\n");

            sb.append("    TrimTitle = \"...\"\n");
            sb.append("    FullscreenAbove = \"True\"\n");
            sb.append("    FullscreenDetect = \"True\"\n");
            sb.append("    HonourRandr = \"True\"\n");
            sb.append("    HonourAspectRatio = \"True\"\n");
            sb.append("    EdgeSize = \"1 1 1 1\"\n");
            sb.append("    EdgeIndent = \"False\"\n");
            sb.append("    DoubleClickTime = \"250\"\n\n");

            sb.append("    Placement {\n");
            sb.append("        Model = \"CenteredOnParent Smart MouseNotUnder\"\n");
            sb.append("        Smart {\n");
            sb.append("            Row = \"True\"\n");
            sb.append("            TopToBottom = \"True\"\n");
            sb.append("            LeftToRight = \"True\"\n");
            sb.append("            OffsetX = \"0\"\n");
            sb.append("            OffsetY = \"0\"\n");
            sb.append("        }\n");
            sb.append("    }\n\n");

            sb.append("    UniqueNames  {\n");
            sb.append("        SetUnique = \"False\"\n");
            sb.append("        Pre = \" #\"\n");
            sb.append("        Post = \"\"\n");
            sb.append("    }\n");
            sb.append("}\n\n");

            sb.append("Menu {\n");
            sb.append("    Select = \"Motion MotionPressed\"\n");
            sb.append("    Enter = \"MotionPressed ButtonPress\"\n");
            sb.append("    Exec = \"ButtonRelease\"\n");
            sb.append("}\n\n");

            sb.append("CmdDialog {\n");
            sb.append("    HistoryUnique = \"True\"\n");
            sb.append("    HistorySize = \"1024\"\n");
            sb.append("    HistoryFile = \"~/.pekwm/history\"\n");
            sb.append("    HistorySaveInterval = \"16\"\n");
            sb.append("}\n\n");

            sb.append("Harbour {\n");
            sb.append("    OnTop = \"True\"\n");
            sb.append("    MaximizeOver = \"False\"\n");
            sb.append("    Placement = \"Right\"\n");
            sb.append("    Orientation = \"TopToBottom\"\n");
            sb.append("    Head = \"0\"\n\n");

            sb.append("    DockApp {\n");
            sb.append("        SideMin = \"64\"\n");
            sb.append("        SideMax = \"0\"\n");
            sb.append("    }\n");
            sb.append("}\n\n");

            sb.append("Files {\n");
            sb.append("    Menu = \"~/.config/nizam/pekwm/menu\"\n");
            sb.append("    Start = \"~/.config/nizam/pekwm/start\"\n");
            sb.append("    Theme = \"~/.config/nizam/pekwm/themes/nizam\"\n");
            sb.append("}\n\n");

            sb.append("Screen {\n");
            sb.append("    Workspaces = \"4\"\n");
            sb.append("    WorkspacesPerRow = \"4\"\n");
            sb.append("    WorkspaceNames = \"Workspace 1;Workspace 2;Workspace 3;Workspace 4\"\n\n");

            sb.append("    Placement {\n");
            sb.append("        Model = \"CenteredOnParent Smart MouseNotUnder\"\n");
            sb.append("    }\n");
            sb.append("}\n\n");

            sb.append("Menu {\n");
            sb.append("    DisplayIcons = \"False\"\n");
            sb.append("}\n");
            return sb.str;
        }

        public string render_keys (WmState st) {
            var sb = new StringBuilder();
            sb.append(header());
            sb.append("Global {\n");
            for (uint i = 0; i < st.keys.length; i++) {
                var key = (WmKey) st.keys.get(i);
                if (!key.enabled) continue;
                var accel = normalize_accel(key.accel);
                sb.append("\tKeyPress = \"%s\" { Actions = \"%s\" }\n".printf(accel, key.action));
            }
            sb.append("}\n");
            return sb.str;
        }

        public string render_autoproperties (WmState st) {
            var sb = new StringBuilder();
            sb.append(header());
            sb.append("Require {\n");
            sb.append("\tTemplates = \"True\"\n");
            sb.append("}\n");
            return sb.str;
        }

        public string render_theme_block (WmState st) {
            var block = get_setting(st, "pekwm.theme.block", "");
            if (block.strip().length == 0) return "";
            var sb = new StringBuilder();
            sb.append(header());
            sb.append(block.strip());
            sb.append("\n");
            return sb.str;
        }

        public string render_start (WmState st) {
            var block = get_setting(st, "pekwm.start.block", "");
            if (block.strip().length == 0) return "";
            var sb = new StringBuilder();
            sb.append(block.strip());
            sb.append("\n");
            return sb.str;
        }
    }
}
