using GLib;

namespace NizamSettingsTests {
    private static string? find_theme_source_from_exe () {
        try {
            var exe = FileUtils.read_link("/proc/self/exe");
            if (exe == null || exe.strip().length == 0) return null;
            var dir = Path.get_dirname(exe);
            for (int up = 0; up <= 10; up++) {
                string rel = ".";
                for (int i = 0; i < up; i++) rel = Path.build_filename(rel, "..");

                var cand1 = Path.build_filename(dir, rel, "nizam-settings", "data", "ui", "pekwm", "theme");
                if (FileUtils.test(cand1, FileTest.IS_DIR)) return cand1;

                var cand2 = Path.build_filename(dir, rel, "data", "ui", "pekwm", "theme");
                if (FileUtils.test(cand2, FileTest.IS_DIR)) return cand2;
            }
        } catch (Error e) {
            
        }
        return null;
    }

    private static uint count_pngs (File dir) throws Error {
        if (!dir.query_exists()) return 0;
        uint count = 0;
        var enumerator = dir.enumerate_children("standard::name,standard::type", FileQueryInfoFlags.NONE);
        FileInfo info;
        while ((info = enumerator.next_file()) != null) {
            if (info.get_file_type() != FileType.REGULAR) continue;
            var name = info.get_name();
            if (name != null && name.has_suffix(".png")) count++;
        }
        return count;
    }

    private static void assert_file_exists (string path, string label) {
        if (!FileUtils.test(path, FileTest.EXISTS)) {
            stderr.printf("Missing %s: %s\n", label, path);
            Process.exit(2);
        }
    }

    private static void assert_contains (string haystack, string needle, string label) {
        if (!haystack.contains(needle)) {
            stderr.printf("Expected %s to contain: %s\n", label, needle);
            Process.exit(2);
        }
    }

    public static int main (string[] args) {
        
        var tmp_root = Path.build_filename(Environment.get_tmp_dir(), "nizam-test-" + Uuid.string_random());
        DirUtils.create_with_parents(tmp_root, 0700);

        var home = Path.build_filename(tmp_root, "home");
        var xdg_config = Path.build_filename(home, ".config");
        var xdg_data = Path.build_filename(home, ".local", "share");
        DirUtils.create_with_parents(xdg_config, 0700);
        DirUtils.create_with_parents(xdg_data, 0700);

        Environment.set_variable("HOME", home, true);
        Environment.set_variable("XDG_CONFIG_HOME", xdg_config, true);
        Environment.set_variable("XDG_DATA_HOME", xdg_data, true);

        
        var theme_src = find_theme_source_from_exe();
        if (theme_src == null) {
            stderr.printf("Could not locate theme sources from dev tree.\n");
            return 2;
        }
        Environment.set_variable("NIZAM_PEKWM_THEME_DIR", theme_src, true);

        string message;
        var status = NizamSettings.PekwmBackend.apply_from_common(out message, null);
        if (status != NizamSettings.PekwmApplyStatus.OK) {
            stderr.printf("Apply failed: %s\n", message);
            return 2;
        }

        
        var managed_dir = Path.build_filename(xdg_config, "nizam", "pekwm");
        var cfg_path = Path.build_filename(managed_dir, "config");
        var menu_path = Path.build_filename(managed_dir, "menu");
        var start_path = Path.build_filename(managed_dir, "start");

        assert_file_exists(cfg_path, "managed config");
        assert_file_exists(menu_path, "managed menu");
        assert_file_exists(start_path, "managed start");

        if (!FileUtils.test(start_path, FileTest.IS_EXECUTABLE)) {
            stderr.printf("Start file is not executable: %s\n", start_path);
            return 2;
        }

        
        try {
            string start_contents;
            FileUtils.get_contents(start_path, out start_contents);
            assert_contains(start_contents, "# Generated by Nizam - DO NOT EDIT", "managed start");
            
            assert_contains(start_contents, "feh --bg-scale", "managed start");
            assert_contains(start_contents, "wallpaper-fallback.png", "managed start");
            
            assert_contains(start_contents, "nizam-panel &", "managed start");
            assert_contains(start_contents, "nizam-dock &", "managed start");
            
            assert_contains(start_contents, "# (none)", "managed start");
            if (start_contents.contains("volumeicon") || start_contents.contains("nm-applet") || start_contents.contains("dropbox")) {
                stderr.printf("Unexpected default autostart entries present in managed start\n");
                return 2;
            }
        } catch (Error e) {
            stderr.printf("Failed reading managed start: %s\n", e.message);
            return 2;
        }

        try {
            string cfg_contents;
            FileUtils.get_contents(cfg_path, out cfg_contents);
            assert_contains(cfg_contents, "# Generated by Nizam - DO NOT EDIT", "managed config");
            assert_contains(cfg_contents, "MoveResize {", "managed config");
            assert_contains(cfg_contents, "CmdDialog {", "managed config");
            assert_contains(cfg_contents, "Menu = \"~/.config/nizam/pekwm/menu\"", "managed config");
            assert_contains(cfg_contents, "Start = \"~/.config/nizam/pekwm/start\"", "managed config");
            assert_contains(cfg_contents, "Theme = \"~/.config/nizam/pekwm/themes/nizam\"", "managed config");
            assert_contains(cfg_contents, "WorkspaceNames = \"Workspace 1;Workspace 2;Workspace 3;Workspace 4\"", "managed config");
        } catch (Error e) {
            stderr.printf("Failed reading managed config: %s\n", e.message);
            return 2;
        }

        
        try {
            string menu_contents;
            FileUtils.get_contents(menu_path, out menu_contents);
            assert_contains(menu_contents, "# Generated by Nizam - DO NOT EDIT", "managed menu");
            assert_contains(menu_contents, "RootMenu = \"Nizam\"", "managed menu");
            assert_contains(menu_contents, "Entry = \"Terminal\" { Actions = \"Exec nizam-terminal &\" }", "managed menu");
            assert_contains(menu_contents, "Entry = \"Explorer\" { Actions = \"Exec nizam-explorer &\" }", "managed menu");
            assert_contains(menu_contents, "Entry = \"Settings\" { Actions = \"Exec nizam-settings &\" }", "managed menu");
            assert_contains(menu_contents, "Entry = \"Stop Window Manager\" { Actions = \"Exit\" }", "managed menu");
            assert_contains(menu_contents, "Entry = \"Restart\" { Actions = \"Restart\" }", "managed menu");
            assert_contains(menu_contents, "WindowMenu = \"\"", "managed menu");
            assert_contains(menu_contents, "Entry = \"Kill Window\" { Actions = \"Kill\" }", "managed menu");
        } catch (Error e) {
            stderr.printf("Failed reading managed menu: %s\n", e.message);
            return 2;
        }

        
        var theme_dst = Path.build_filename(managed_dir, "themes", "nizam");
        var theme_file = Path.build_filename(theme_dst, "theme");
        var svg_dir = Path.build_filename(theme_dst, "svg");
        var png_dir = Path.build_filename(theme_dst, "png");

        assert_file_exists(theme_file, "theme file");
        if (!FileUtils.test(svg_dir, FileTest.IS_DIR)) {
            stderr.printf("Missing svg dir: %s\n", svg_dir);
            return 2;
        }
        if (!FileUtils.test(png_dir, FileTest.IS_DIR)) {
            stderr.printf("Missing png dir: %s\n", png_dir);
            return 2;
        }

        try {
            var png_count = count_pngs(File.new_for_path(png_dir));
            if (png_count == 0) {
                stderr.printf("No PNGs generated in: %s\n", png_dir);
                return 2;
            }
        } catch (Error e) {
            stderr.printf("Failed scanning PNG dir: %s\n", e.message);
            return 2;
        }

        
        var xinitrc = Path.build_filename(home, ".xinitrc");
        assert_file_exists(xinitrc, "xinitrc");
        try {
            string x_contents;
            FileUtils.get_contents(xinitrc, out x_contents);
            assert_contains(x_contents, "exec pekwm --config ~/.config/nizam/pekwm/config", "xinitrc");
        } catch (Error e) {
            stderr.printf("Failed reading xinitrc: %s\n", e.message);
            return 2;
        }

        var pekwm_dir = Path.build_filename(home, ".pekwm");
        if (FileUtils.test(pekwm_dir, FileTest.EXISTS)) {
            stderr.printf("Unexpected ~/.pekwm created: %s\n", pekwm_dir);
            return 2;
        }

        stdout.printf("OK: %s\n", message);
        return 0;
    }
}
